# Generated by Django 3.1.7 on 2021-04-19 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210417_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='note',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='descritipon',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
