# Generated by Django 3.1.7 on 2021-04-20 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20210420_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(blank=True, default='Image.png', null=True, upload_to=''),
        ),
    ]
